apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-llm-serving
  namespace: llmops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-serving
  template:
    metadata:
      labels:
        app: llm-serving
    spec:
      containers:
      - name: ollama-engine
        image: ollama/ollama:0.1.34
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
          name: llm-port
        resources:
          requests:
            cpu: "2000m"
            memory: "8Gi" # Llama3 구동을 위한 로컬 PC 메모리 예약 (Guaranteed QoS)
          limits:
            cpu: "3500m"
            memory: "8Gi"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 10 && ollama pull llama3"]

        ports:
        - containerPort: 11434
          name: llm-port
          
        # [추가] 모델 다운로드가 끝날 때까지 K8s가 최대 10분간 컨테이너 강제 재시작을 유예함
        startupProbe:
          httpGet:
            path: /
            port: 11434
          failureThreshold: 60
          periodSeconds: 10
          
        # [추가] 모델이 온전히 메모리에 로드되어 실제 트래픽을 받을 준비가 되었는지 검증
        readinessProbe:
          httpGet:
            path: /
            port: 11434
          periodSeconds: 10