---
- name: K3s 워커(Agent) 설치 및 설정 업데이트
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars['master']['ansible_host'] }}:{{ k3s_port }}" \
    K3S_TOKEN="{{ hostvars['master']['join_token'] }}" sh -s - agent \
    --node-ip="{{ ansible_host }}" \
    --flannel-iface=eth1
  args:
    creates: /usr/local/bin/k3s
  register: k3s_agent_install_result
  notify: restart k3s-agent