---
- name: "01단계: 앤서블 로컬 환경 셋업 (컬렉션 설치)"
  hosts: localhost
  connection: local
  tasks:
    - name: "requirements.yml에 정의된 컬렉션 설치"
      command: ansible-galaxy collection install -r ../requirements.yml
      register: galaxy_install
      changed_when: "'is already installed' not in galaxy_install.stdout"