# Cloudflare Tunnel 토큰을 암호화하여 Git에 안전하게 저장하는 SealedSecret
# TUNNEL_TOKEN은 Cloudflare 대시보드에서 발급한 터널 토큰을 kubeseal로 암호화한 값
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token
  namespace: monitoring
spec:
  encryptedData:
    TUNNEL_TOKEN: AgA7tZD1hZ9Yg0VGCQnCIIbKwP1BAwL5YLPtKVG7kndrQys/4mwBj75QR27WXH7+jMcid22zE/uiOO6eve4jZYdfh4ubMqM5/7+sS6OkddRPwROMfm7oGe8z1b5fl1Yd+VgHQUjMyq2cIzyN6IhE25F2LnD3fmb95AksH43by9vHpEPiqXjvEs+jah1HlEGGxwcH31aGqhztxW8Fz1mxobfxshWfjPyoz0FkeNQL7afutEV8IJyNlknnG5uDUfzsgNFtwYBe40A8RjG3s17S6ClOSF2XJbhfSsGkqDKX124vrNuNro+Df+abOmxCnpB7+d5218I1cteAsY3RnoXWsBtq1D4zKsYnbragVnsumJfoBSFMaUI+iGodZ24Lse71y8VSh9t6p/xTb/T3gcZYaGPIrV1Of50qDrsmGpJsBHAFXHozG3gi7+4NS+uG2Xny1zA0Q7nco5eK6USc87ilxkf/M4HCXdvvM/DvL8EGs6HzEIlzFCaEqZPl9yypCMe7uoKzOxXDLRPMrBAbv0RrF/jEeKF8OGPPxJZWE9bFROosiM2ncgA3RH2K52RTIENpyTVuw2PHb1Ux+QENqHDDBF1OAqkcZ1WDAItTIl+fmRqpDuHzNc0b4c2ldGyJzeFpP/yOr9FKR5aHkLiOMIF3L5FVSrWMS5EqDFMG2MMwlMsgwRp2yHyCjajPkqkBXPf18CLVuyMi/1QNwbNamdxmDXdq2o0PzTd1biIDXRwhEmKz9vgyZKcq+uXOb/ewNJKz2pT///Dob+AO3Hg6HHCf0fHi+9BcZETpALgaUPBNXJ99liMsOvdDVWRj7ea0Qxej4Cki2BfVFIZWTNal5FOFOcX3p2PMsr57KhCOfaWotF/Eb7hOTvnZYUfikaihlsQIxaBfMnSABd+q+aPU+IQHqeBUlGacgzxMZbueHlcwqWtvh+6CpTNgf3NH
  template:
    metadata:
      name: cloudflare-token
      namespace: monitoring
