[local]
localhost ansible_connection=local

[control-plane]
master ansible_host=192.168.56.10

[web]
web-node-01 ansible_host=192.168.56.11
web-node-02 ansible_host=192.168.56.12

[db]
db-node-01 ansible_host=192.168.56.13

[workers:children]
web
db

[cluster:children]
master
workers

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant