apiVersion: v1
kind: Service
metadata:
  name: service-vector-db
  namespace: llmops
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: vector-db
  type: ClusterIP