name: apply

on:
  workflow_dispatch:

jobs:
  deploy-infra-and-configure:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Terraform 설치
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform 초기화 및 배포
        run: |
          terraform init -reconfigure
          terraform apply -auto-approve

      - name: "[통합] 인스턴스 인식 및 설정 스크립트 전송"
        shell: bash
        run: |
          # Terraform Output을 환경 변수로 추출 (-chdir 옵션 삭제)
          export AWS_VPC_CIDR=$(terraform output -raw vpc_cidr) # 10.0.0.0/16을 자동으로 가져옴
          export ONPREM_VPC_CIDR=$(terraform output -raw onprem_vpc_cidr) # 192.168.0.0/24를 자동으로 가져옴
          export TUNNEL1_IP=$(terraform output -raw vpn_tunnel1_ip)
          export TUNNEL1_PSK=$(terraform output -raw vpn_tunnel1_psk)
          export BGP_PEER1_IP=$(terraform output -raw vpn_bgp_peer1_ip)
          export BGP_LOCAL1_IP=$(terraform output -raw vpn_bgp_local1_ip)
          export TUNNEL2_IP=$(terraform output -raw vpn_tunnel2_ip)
          export TUNNEL2_PSK=$(terraform output -raw vpn_tunnel2_psk)
          export BGP_PEER2_IP=$(terraform output -raw vpn_bgp_peer2_ip)
          export BGP_LOCAL2_IP=$(terraform output -raw vpn_bgp_local2_ip)

          # 분리된 스크립트 실행
          chmod +x ./scripts/setup_vpn.sh
          ./scripts/setup_vpn.sh